In [3]:
import numpy as np
from scipy.sparse import csr_matrix
  
sparseMatrix = csr_matrix((3, 4), 
                          dtype = np.int8).toarray()
  
print(sparseMatrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
 row = np.array([0, 0, 1, 1, 2, 1])
 col = np.array([0, 1, 2, 0, 2, 2])
  
 data = np.array([1, 4, 5, 8, 9, 6])
  
 sparseMatrix = csr_matrix((data, (row, col)), 
                          shape = (3, 3)).toarray()

    
 print(sparseMatrix)

[[ 1  4  0]
 [ 8  0 11]
 [ 0  0  9]]
